#!/usr/bin/env bash
#use case to display various messages throughout an iteration
i=1
while ((i <= 20)); do
	case $i in
		4)
			echo $i
			echo bad luck from China;;
		9)
			echo $i
			echo back luck from Japan;;
		17)
			echo $i
			echo bad luck from Italy;;
		*)
			echo $i;;
	esac
	((i++))
done
