#!/usr/bin/env bash
#use case to display various messages throughout an iteration
i=1
while ((i <= 20)); do
	case $i in
		4)
			echo bad luck from China
			echo $i;;
		9)
			echo back luck from Japan
			echo $i;;
		17)
			echo bad luck from Italy
			echo $i;;
		*)
			echo $i;;
	esac
	((i++))
done
