#!/usr/bin/env bash
#display every minute and hour for 12 hours and 59 minutes
hour=0
minute=0
while ((hour <= 12)); do
	echo Hour: $hour
	minute=0
	while ((minute <= 59)); do
		echo $minute
		((minute++))
	done
	((hour++))
done
